#  ___        _  ___           __ _
# | _ \___ __| |/ __|_ _ __ _ / _| |_   ___ _ _ __ _
# |   / -_) _` | (__| '_/ _` |  _|  _|_/ _ \ '_/ _` |
# |_|_\___\__,_|\___|_| \__,_|_|  \__(_)___/_| \__, |
#                                              |___/
#

# We'll do all of our averages checks over a time frame to rubber band players if they travel too fast
# Lower values will avoid log earlier but can lead to false positives,
# especially when a player teleports to unloaded chunks
time-frame-seconds: 5.0

# Amount of already generated chunks a player can load within the set time frame before getting rubber-banded
# Generating new terrain using vanilla Elytras and rockets will be 380-420 chunks per second
# The default value of 450 should never punish a vanilla player but might not be the best if you want to allow
# hacked clients on your server
load-limit-per-second: 450

# This is the modifier for newly generated chunks
# By default generating 1 chunk counts as 8 chunks because generating chunks is resource intensive
generation-modifier: 8

# This defines how far the player will be pushed back, it depends on the velocity
# Players with the permission "antigenerationlag.norubberband" will not be rubber banded or warned
rubber-band-modifier: 50.0

# This is to warn players that they've been rubber-banded
warn-player: true
warn-message: "&cYou're going too fast, please lower your speed and wait for chunks to load"

# This is to freeze the player, it's very effective when using hacks to force slowing down
# By default we check frozen players every 10 ticks it's a good compromise for performance
freeze-player: true
freeze-duration-seconds: 5.0
freeze-check-tick-interval: 10

# This is to debug speed that will be send to players with the permission "antigenerationlag.debug"
debug-speed: false
